### ISSUE TITLE
Handle RTC file transfert

### ISSUE THREAD

**Issue by dani** [HenrikJoreteg/SimpleWebRTC#105]
Would be great if SimpleWebRTC could also handle arbitrary file transfert between peers through dataChannels (chunk size negociation, chunk/unchunk etc...). The WebRTCCopy project can probably give some inspiration, see https://github.com/erbbysam/webRTCCopy

**Comment by fippo** [comment]
now supported in 1.15.0 -- see https://github.com/HenrikJoreteg/SimpleWebRTC/pull/213
