### ISSUE TITLE
How do i set fixed audio/video bitrate?

### ISSUE THREAD

**Issue by shamun** [HenrikJoreteg/SimpleWebRTC#150]
While using apprtc.appspot.com i had option to set manually audio/video upload/download bitrate:
var audioSendBitrate = '50';
var audioRecvBitrate = '50';
var videoSendBitrate = '100';
var videoRecvBitrate = '100';
var videoSendInitialBitrate = '100';

In SimpleWebRTC how do i set that please?

**Comment by esevece** [comment]
@envery solution works for me.
