### ISSUE TITLE
Implementing "user is speaking events"

### ISSUE THREAD

**Issue by latentflip** [HenrikJoreteg/SimpleWebRTC#16]
Hey @HenrikJoreteg et al.

I am working on implementing the sending of events between clients to indicate who is speaking. This would allow video switching/indicators like in google hangouts etc.

I have a first cut working (will get code up in a pull request soon), but there's still some work to do.

I have some questions/thoughts:
* Should we be sending a polling event every n milliseconds when a user is speaking to indicate they are still speaking? Or should we just send an event when they start and another event when they finish? Any naming convention for these events that we prefer?
* I should be emitting the events to all the peer connections right?
* The code will need a `volume_threshold` to determine when a user is actually speaking, and some kind of a timeout to allow for brief pauses in speech without a `speaking_finished` being emitted. Should these numbers be configurable, or should we be opinionated about it.

Would love any thoughts/opinions :)

Phil

**Comment by xdumaine** [comment]
Closing; this has been working with the latest update's description for some time now.
