### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by wilguevara** [HenrikJoreteg/SimpleWebRTC#172]
Hello ! i'm trying to deploy the project to heroku, have you tried this before? is there any issues? Thanks!

**Comment by jlengstorf** [comment]
@wilguevara I've done it without issues. I combined it with the signaling server (https://github.com/andyet/signalmaster) in a single Node app: back-end for signaling, front end for SimpleWebRTC. No problems getting it to run.

Good luck!

**Comment by wilguevara** [comment]
@jlengstorf me too, by the way thanks for your reply!
