### ISSUE TITLE
Latest.js not generated

### ISSUE THREAD

**Issue by Superlukec** [HenrikJoreteg/SimpleWebRTC#196]
When I build the project it only outputs "simplewebrtc.bundle.js" and not "latest.js". 

I use command "node build". Am I doing something wrong?

Thank you for your help.

**Comment by fippo** [comment]
building latest.js is currently broken, should be working again once I merge #195 
If you want to build in the meantime, remove the :8888 in build.js

**Comment by Superlukec** [comment]
Ok. Thank you for your quick reply!
