### ISSUE TITLE
How can i setup the upload download per candidate while using MCU?

### ISSUE THREAD

**Issue by shamun** [HenrikJoreteg/SimpleWebRTC#200]
I have a scenario for University Belgium where i need to do as following:

1 - Physics Professor starts the class at 9AM, his video, audio is active
2 - Physics Students join the class 10, 20, 50, 90, 100, 200 students depends
3 - Professor can see all the students and hear the students (interactive is full-duplex with professor to student)

4 - Students can see Professor and hear Professor, but Students can not see other Students nor can Hear others.

While using MCU module of SimpleWebRTC how can i achieve this please? ( i have always full-duplex video, audio, how can i tell SimpleWebRTC that do not download video to save bandwidth and also do not download audio from all others except 1 person in MCU?)

Please advise.

**Comment by fippo** [comment]
file an issue on the mcu module please.
