### ISSUE TITLE
Error on using library

### ISSUE THREAD

**Issue by timotius02** [HenrikJoreteg/SimpleWebRTC#202]
GET https://signaling.simplewebrtc.com:8080/socket.io/1/?t=1423377575466 net::ERR_CONNECTION_TIMED_OUT

Most likely because of socket.io incompatibility

**Comment by fippo** [comment]
pass url: 'https://signaling.simplewebrtc.com:443' to the constructor  -- when running on a nonstandard port it tries to connect to the same port and there is nothing running on port 8080
