### ISSUE TITLE
Screen sharing stopped working in latest Canary but working with Google Chrome Stable

### ISSUE THREAD

**Issue by shamun** [HenrikJoreteg/SimpleWebRTC#204]
Just tested: https://talky.io

- Using Google Version 42.0.2301.0 canary (64-bit)  from OSX 10.9.5
- Locally it shows its working but remotely not receiving, even though it says established 
(remotely also used Google Chrome stable and Canary latest)

Can you please check kindly and confirm if its BUG from Canary or with talky?

Seems be something has been broken down the screen sharing since Canary.

**Comment by fippo** [comment]
can't reproduce on either windows, linux or mac with that version. 
And this is neither the talky.io bugtracker nor the chrome bugtracker. AreYouTrying?

**Comment by shamun** [comment]
yes i am trying and testing but still same. 

SimpleWebRTC is used same problem (talky.io mentioned as reference here). See below Canary sending screen but Chrome is black screen. Same problem with talky.io or with SimpleWebRTC only if used.

![screen shot 2015-02-11 at 22 03 22](https://cloud.githubusercontent.com/assets/107349/6156377/0f2f5dfa-b23a-11e4-8cf9-718203eefd20.png)

**Comment by fippo** [comment]
@marwahvikas I can't reproduce. Do you know of any changes in canary that might affect screensharing? Might be indirect, e.g. handling of large packets  in bad network conditions?

**Comment by shamun** [comment]
FYI - still not working.

Just now uninstalled Google Chrome, Canary, Windows 8 - 64-bit. Re-installed Windows 8-64-bit fresh copy and installed Google Canary fresh copy.

- Tried the same test and still its failing with Google Canary
- Tried the same test with Google Chrome stable and it works like always
- Also same issue just tested with OSX 10.9.5 (by refreshing and re-installing everything to be sure if no other extensions were conflicting)

**Comment by marwahvikas** [comment]
I will give a try and follow up.

**Comment by marwahvikas** [comment]
Could not recreate it, can you also verify if it works with google hangouts or not for you. Seems to work fine for me.

**Comment by shamun** [comment]
@marwahvikas: this is very very very weird. 

Right now i tried talky.io and simplewebrtc both is working with Canary(just yesterday i tested, and it was not working at all, suddenly now its working again, very weird)

Thank you for your support.
(Can we leave this issue temporary open please? i will try to instal other extensions and if still it works then i will close the issue later)
