### ISSUE TITLE
stop screen share didn't clear remote side view

### ISSUE THREAD

**Issue by changgb** [HenrikJoreteg/SimpleWebRTC#206]
User A share screen to User B, when User A call stopScreenShare(), it seems User B still show video element of user A's last screen, at the same time, User B can't get VideoRemoved event ( I remember back to 6 month ago it works). I am not sure it's a new bug or I  know to call any other api to notify User B's browser before I call stopScreenShare, any one can help me? Thanks.

**Comment by shamun** [comment]
Can not recreate it. Please test with latest version of Canary and Google Chrome stable.

**Comment by changgb** [comment]
tested on latest Google Chrome stable(40.0.2214.111) both window and Mac, will try demo website at home, in company can't share screen

**Comment by fippo** [comment]
@changgb what version are you using? Do you have a demo where I can test? If not: can you inspect the websocket connection and see if anything is sent over it?

**Comment by shamun** [comment]
@changgb: also, can you please also try to check your Google Chrome existing `chrome://extensions/` ? And can you please try following:

1 - remove the existing extensions 
2 - restart the chrome and only install talky.io extension
3 - then make connection see if it solve or not?


NOTE: i had strange issue with Canary but its solve now, but i could not reproduce your problem in my Chrome stable nor in Canary

**Comment by changgb** [comment]
@shamun, I can't try demo site, the sharescreen button is disabled
![screen shot 2015-02-16 at 10 36 26 am](https://cloud.githubusercontent.com/assets/3435630/6206575/46d17112-b5c8-11e4-9f54-0a5475c9f65c.png)

@fippo, I forget which version I used, you can use this link to test.

https://vc.tspl.com.sg/spa.html#/conf?id=54e1503b7cf886271bbcf3fa&t=1424052900000&p=1&pin=53245826

**Comment by changgb** [comment]
@fippo, even the latest version I tried on my laptop, 1.13.1, failed to close remote side shared screen

**Comment by fippo** [comment]
@changgb I didn't see a screenshare button in your test link?

**Comment by changgb** [comment]
@fippo sorry the URL is:
https://vc.tspl.com.sg/spa.html#/conf?id=54e1503b7cf886271bbcf3fa&t=1424052900000&p=1&pin=46019280

screen share button is the third one below your video.

**Comment by changgb** [comment]
@fippo I found this between talky.io and my website: on talky.io websocket send remove message to signal server, my website no remove message from client to signal server, I am still finding what caused this difference, can you tell me how to find this out?

talky.io
![screen shot 2015-02-23 at 10 55 20 am](https://cloud.githubusercontent.com/assets/3435630/6322532/38976cb2-bb51-11e4-9d32-6beda8e702c0.png)

my website

![screen shot 2015-02-23 at 11 37 10 am](https://cloud.githubusercontent.com/assets/3435630/6322535/46f0f13e-bb51-11e4-986f-c0958cc7a60f.png)

**Comment by fippo** [comment]
as far as I can see, your site is also sending the unshareScreen from client to server -- but it never arrives at the other client.
What happens if you add debug to https://github.com/andyet/signalmaster/blob/master/server.js#L82-86 -- is client.room set?

**Comment by changgb** [comment]
Thanks fippo, I keep check client side problem, forget the server side. I changed client.room to meeting_id, but forgot to change inside unshareScreen event, now fixed. Thanks very much for your help

**Comment by fippo** [comment]
fab!
