### ISSUE TITLE
SimpleWebRTC failed  - ICMP ping blocked, but HTTPS, HTTP, WebSocket all allowed by enterprise

### ISSUE THREAD

**Issue by shamun** [HenrikJoreteg/SimpleWebRTC#209]
Some enterprise block Turnserver, Signal server ICMP ping, but all the rest works such as https://talky.io or reach https://turnserver.ip

But if you are doing ping to the same ip there is no ICMP ping response (because the enterprise block ICMP). As a result SimpleWebRTC is not working in those network.

How to resolve in this scenario? (you can see camera / microphone is active you can browse http, https but cant ping ips)

**Comment by fippo** [comment]
You might want to read https://tools.ietf.org/html/draft-hutton-rtcweb-nat-firewall-considerations

If talky.io works then that suggests your case can be solved with the right TURN configuration.

**Comment by shamun** [comment]
@fippo: sorry i mean to say talky, SimpleWebRTC also does not work when the ICMP ping is disabled.

**Comment by shamun** [comment]
FYI - Here is the scenario:

1 - Enterprise do not allow ICMP ping to outside world
2 - Google chrome stable you browse https://talky.io or simplewebrtc sites, it opens perfectly fine, then you feel its working or will work because you see the page is loaded and also you are able to load your media (cam, mic)
3 - now you want to make real connect with remote end users, then it fails to establish the connection always shows "connecting..." but never connects

NOTE: temporary we enabled the ICMP ping from that location and then connection is working on the fly

**Comment by fippo** [comment]
Does apprtc work in the same case? If it doesn't ...

**Comment by shamun** [comment]
AppRTC - i have not tried but basically i have fall-back algorithm such as 1) first attempt with talky.io if no connection within 10 seconds go to SimpleWebRTC if no connection with it 10 second then finally on 30 second try AppRTC 2) i think all failed because i have automated Diagnostic testing tool which use those 3 services at once

But i will later try to manually test AppRTC too, i think its the same issue with all. I also remember i had same problem with European Commission network long time ago and our project was rejected because of this issue.

**Comment by shamun** [comment]
I have simulated the test again in my lab, where ICMPv4 and ICMPv6 protocol set into disable outgoing mode with PC running Linux CentOS 7, OSX 10.10.2, Windows 8.

FYI


1 - From those PC's i was unable to do general ICMP ping to Talky and AppRTC servers + iTesting servers.
2 - But when i tried to make call. On every attempt calls were working with Talky with AppRTC with iTesting

Then i by force disabled few things for turnserver related traffics, then i was successfully able to simulate that problem i faced on-site with enterprises. 

So to make long story short, this only happening not for only by blocking ICMP protocol, but something towards turnserver will cause.

(we can close this issue thank you)

**Comment by fippo** [comment]
(you can close your own issues)
