### ISSUE TITLE
Error while connecting, connection fail

### ISSUE THREAD

**Issue by shamun** [HenrikJoreteg/SimpleWebRTC#217]
Today i faced one strange problem using SimpleWebRTC. Let me explain:

1) Scenario:

Behind same network 3 PC trying to connect each PC has following:

PC1 = iframe1: https://simplewebrtc/candidateA
           iframe2: https://simplewebrtc/candidateB
PC2 = https://simplewebrtc/candidateA
           iframe1: https://simplewebrtc/candidate_ab
PC3 = https://simplewebrtc/candidateB
        = iframe1: https://simplewebrtc/candidate_ab

NOTE:
PC1 connects PC2 and PC3 to do Audio only session (P2P they do not see each other)
PC2 and PC3 connects with each other Video only session (P2P they do not hear each other)

2) Same code, works for me in my test lab, and also my office lab networks without any problem at all.

3) But today we went to customer network, we setup the same PC's and it fail to connect with exceptions on this line "if (update.candidate.candidate.indexOf('a=') !== 0) {"

4) We stop using the way we are using and then simply manually we used P2P url straight with each PC's and with same library without any problem, it worked.

5) After point 4, we used on customer network only one PC2 (to avoid port conflicts or public ip related issues). no other PC's where used in there network except 1, and the rest 2 PC, we simulated from my lab and office lab networks.  So 3 unique locations with unique networks. 
Then it again worked.

6) When we used SimpleWebRTC in MCU mode but not all of the PC's were showing video stream or audio stream (behind customer network).

```
// Init and add ice candidate object with correct constructor
PeerConnection.prototype.processIce = function (update, cb) {
    cb = cb || function () {};
    var self = this;

    if (update.contents) {
        var contentNames = _.pluck(this.remoteDescription.contents, 'name');
        var contents = update.contents;

        contents.forEach(function (content) {
            var transport = content.transport || {};
            var candidates = transport.candidates || [];
            var mline = contentNames.indexOf(content.name);
            var mid = content.name;

            candidates.forEach(function (candidate) {
                var iceCandidate = SJJ.toCandidateSDP(candidate) + '\r\n';
                
                console.log('>>> ' + iceCandidate);
                
                self.pc.addIceCandidate(new webrtc.IceCandidate({
                    candidate: iceCandidate,
                    sdpMLineIndex: mline,
                    sdpMid: mid
                })
                /* not yet, breaks Chrome M32 */
                /*
                , function () {
                    // well, this success callback is pretty meaningless
                },
                function (err) {
                    self.emit('error', err);
                }
                */
                );
                if (candidate.type === 'srflx') {
                    self.hadRemoteStunCandidate = true;
                }
                else if (candidate.type === 'relay') {
                    self.hadRemoteRelayCandidate = true;
                }
            });
        });
    } else {
      try{
        // working around https://code.google.com/p/webrtc/issues/detail?id=3669
        if (update.candidate.candidate.indexOf('a=') !== 0) {
            update.candidate.candidate = 'a=' + update.candidate.candidate;
        }

        console.log('>>> ' + update.candidate.candidate);
        //update.candidate.candidate = update.candidate.candidate.replace("host", "relay");
        //update.candidate.candidate = update.candidate.candidate.replace("srflx", "relay");
        
        self.pc.addIceCandidate(new webrtc.IceCandidate(update.candidate));
        if (update.candidate.candidate.indexOf('typ srflx') !== -1) {
            self.hadRemoteStunCandidate = true;
        }
        else if (update.candidate.candidate.indexOf('typ relay') !== -1) {
            self.hadRemoteRelayCandidate = true;
        }
        
      }catch(e) {
        console.log(">>> WHY??? " , e);
      }
    }
    cb();
};
```

Why its failing when mentioned scenario point 1 was used?
Why its not failing when point 4, 5 used?
Why point 6 failed to established video / audio stream? when we are behind there network?

Can you advise please?

**Comment by fippo** [comment]
latest canary has a bug apparently, avoid it for now.

**Comment by shamun** [comment]
@fippo :  OK - Thank you.


FYI 
Unfortunately i believe they used Google Chrome stable today, which actually failed. 
(I will be tomorrow onsite for more details testing, its for one European Commission pilot project)

I need to identify tomorrow there network and see if its also there personal PC firewall related or not. Mostly they use windows os, where they have to login to there domain servers or so.

**Comment by fippo** [comment]
canary issue should be fixed in 1.15.3

**Comment by iamwave007** [comment]
Thank you fippo!!!!!!

**Comment by shamun** [comment]
@fippo: i am testing 1.15.3 but got stuck.

in previous version i was using `io.connect` for handling my third party services. But now its removed, how can i get the `io.connect` inside `function SimpleWebRTC(opts) { }`  please i do not want to use the existing `var SocketIoConnection = require('./socketioconnection');` ? as its using this.connection only

```
function SocketIoConnection(config) {
    this.connection = io.connect(config.url, config.socketio);
}
```

Is there any way to get the io.connect like in past i was doing as following and it was working as stable:

```
    connection_custom = this.connection_custom = io.connect('https://server.server.com');
    connection_custom.on("connect", function () {
      console.log('connection_custom: >>>>>>>>>>>>>>>>>>>>>>> connected');
      connection_custom.emit("joinChannel", {
          channel: channel,
          username: username,
          message: '>>> connected'
      });
    });

```

Should i change the function as following without breaking anything?
```
function SocketIoConnection(config) {
    this.connection = io.connect(config.url, config.socketio);
    this.connection_custom = io.connect ('https://server.server.com');   // Add my new independent connections??
}
```

**Comment by shamun** [comment]
OK - never mind made the compatibility. later i will test further and let you guys know. thanks a lot.

```
function SimpleWebRTC(opts) {
   var config = this.config = {
               url: 'https://turn.server.com',
            socketio: {/* 'force new connection':true*/},
            connection: null,
            connection_custom: null,
  .....
    connection_custom.on("connect", function () {
      console.log('connection_custom: >>>>>>>>>>>>>>>>>>>>>>> connected');
      connection_custom.emit("joinChannel", {
          channel: channel,
          username: username,
          message: '>>> connected'
      });
    }); 
}
function SocketIoConnection(config) {
    this.connection = io.connect(config.url, config.socketio);
    this.connection_custom = io.connect('https://server.server.com');
}
```

**Comment by shamun** [comment]
@fippo : thank you once again. 

FYI - for the record of test result

- it was indeed Canary issue with old version, in the same PC when i used Chrome stable it worked
- Then i upgraded the library to the recommended version 1.15.3 and then in Canary also now it was working
