### ISSUE TITLE
webRTC on surface pro 3

### ISSUE THREAD

**Issue by theDude30** [HenrikJoreteg/SimpleWebRTC#218]
Hi,
I'm experiencing issues in displaying remote video in microsoft surface pro 3 on chrome browser.
Are you aware of any issues in that platform? 
on the spec it should be same as a normal PC but it does not work well.

**Comment by fippo** [comment]
i've heard about some issues related to screensharing on a surface, but nothing else.

@marwahvikas might know more?

**Comment by marwahvikas** [comment]
Does apprtc on loopback also fails?  Some logs or chrome://webrtc-internals dump would be useful. Btw someone posted on discuss forum similar issue https://groups.google.com/forum/#!searchin/discuss-webrtc/surface/discuss-webrtc/H4PL_ZIJ8Sk/kNKCnDU6faIJ

**Comment by xdumaine** [comment]
I have a SimpleWebRTC based app that works with remote video and screen sharing on a Surface Pro 3.
