### ISSUE TITLE
Agent self-view mirrored, how to fix it please?

### ISSUE THREAD

**Issue by shamun** [HenrikJoreteg/SimpleWebRTC#222]
Self-view mirrored, but after connection shows correct. 
How to fix it please? (it should show the letters correctly readable which is correct format for default: Talky, AppRTC is invalid, OpenWebRTC is showing it correctly only)

![screen shot 2015-03-30 at 21 57 10](https://cloud.githubusercontent.com/assets/107349/6905383/d792d134-d727-11e4-8efc-d0d574db576b.png)

**Comment by shamun** [comment]
When i use:

            localVideo: {
                autoplay: true,
                mirror: false,
                muted: true
            }

then the image is completely stretched (not same as mirror: true), can you please have a look.

**Comment by shamun** [comment]
When i use mirror: false then the picture in picture (is not same)

**Comment by shamun** [comment]
To get the letters correct in self-view i used `mirror: false`, but then the self-view is not valid anymore, its not natural anymore, its totally stretched out left-right-top-bottom, that is not correct view.

It should keep it as it was when you use mirror: true

**Comment by fippo** [comment]
Use or don't use (depending on what you want) scaleX(-1) for the transform? That's just CSS

**Comment by shamun** [comment]
OK - no problem thank you. I thought the mirror: false should do those (temporary i am using CSS just to inform you)

**Comment by fippo** [comment]
afaics mirror: false works as intended.

**Comment by shamun** [comment]
YES - sorry its correct. i had my code problem where i was using scaleX(2) for #localVideo as a result it was not showing natural camera view. Thank you, its my mistake.

```
    if (opts.mirror) {
        ['', 'moz', 'webkit', 'o', 'ms'].forEach(function (prefix) {
            var styleName = prefix ? prefix + 'Transform' : 'transform';
            element.style[styleName] = 'scaleX(-1)';
        });
    }
```
