### ISSUE TITLE
trying to hit the server via socket io wrapper

### ISSUE THREAD

**Issue by ajitha3008** [HenrikJoreteg/SimpleWebRTC#227]
Hi,

I am trying to hit the simplewebrtc signaling server using socket-io wrapper provided for Android by nkzawa. The transports are sent in query String. but when i hit your server, I am getting timeout error. So am unable to connect to websocket created using socket io wraper by nkzawa. it says transport=undefined. ... I am using with/hitting from android native code. Can you please clarify?

**Comment by fippo** [comment]
timeout error sounds like you're trying to connect to the wrong port -- the sandbox server is listening on port 443

(standard disclaimer: don't use the sandbox server, run your own)

**Comment by ajitha3008** [comment]
Thanks.  Ya,  we hosted own customised server and resolved...
