### ISSUE TITLE
CPU problems

### ISSUE THREAD

**Issue by poshetz** [HenrikJoreteg/SimpleWebRTC#233]
Sorry for another issue, but i find difficult to understand why (using the demo example) the CPU goes up to 45% and chrome is slow if i open a new tab

I am testing with two chrome tabs (if i use firefox CPU is too much high really)

I tried also the direct chat on https://talky.io/ and the demo here http://simplewebrtc.com/demo.html and it's the same, most of the times the CPU has peaks of 45/48% and the middle range is 38/41% per tab

I am wondering if something is producing this charging or if it's normal, since trying for example https://vline.com CPU stay between 30/35%

Thank you again!

**Comment by fippo** [comment]
does it also happen on apprtc.appspot.com? Generally that's a browser problem and there is little one can do (such as reducing the capture size and or framerate)

Google has some undocumented flags to deal with this though.

**Comment by poshetz** [comment]
@fippo  just tested apprtc and it never goes up to 39% here.

While (tested again) talky.io is about 42/47%  i don't understand why since, as streams comes they are pushed into the remote video, is there anything charging toom uch the dom ? i don't know... :(

**Comment by poshetz** [comment]
Ok tested with 2 different PCs on apprtc it's the same so it's not a library problem sorry for that.

If you still have some tip and suggestion to leave a good video quality but slow down the CPU usage that is appreciated, thank you man!

**Comment by fippo** [comment]
video encoding is just very expensive -- chrome 42 just managed to reduce the cpu load but it's still expensive.

check https://test.webrtc.org/ and http://webrtc.github.io/samples/src/content/getusermedia/resolution/ --- passing the same constraints into simplewebrtc is done via the media object in the constructor

**Comment by poshetz** [comment]
thanks :+1:
