### ISSUE TITLE
When remote stream arrive

### ISSUE THREAD

**Issue by poshetz** [HenrikJoreteg/SimpleWebRTC#234]
A simple question, how do i know when remote Stream arrives?

Even better when remote stream is attached to the DOM if possible

**Comment by fippo** [comment]
that's not so simple... and there documented http://simplewebrtc.com/notsosimple.html#basic-overlay and http://simplewebrtc.com/notsosimple.html#connstates

**Comment by poshetz** [comment]
lol so it's not that simple but it's really simple, correct? :D
