### ISSUE TITLE
How to load multi local video at the same time?

### ISSUE THREAD

**Issue by eshengsky** [HenrikJoreteg/SimpleWebRTC#236]
From https://talky.io , I found that after I select my camera & microphone, it shows two local video in page: one is on the modal dialog, and the other is behind the cover layer. Now I wonder how to realize it?
Thanks a lot!

**Comment by fippo** [comment]
if you listen for the localStream event, you get a stream that you can attach using https://github.com/henrikjoreteg/attachmediastream

**Comment by eshengsky** [comment]
Got it. Thanks!
