### ISSUE TITLE
How to set width and height of video with custom aspect ratio?

### ISSUE THREAD

**Issue by eshengsky** [HenrikJoreteg/SimpleWebRTC#239]
I found that the video element has a finxed aspect ratio,for example, I want to show the video as width 400px and height 200px, but it just shows 200px and left blank in width. 
Could someone help me? Is it possible to set my coustom aspect ratio?

**Comment by xdumaine** [comment]
Browsers have a fixed set of resolution results that can be delivered. The best way you can do this would be to get a stream of a size larger than you'd like to display and use css to size and crop the video to what you need.

**Comment by eshengsky** [comment]
@xdumaine got it..thanks!
