### ISSUE TITLE
One way broadcasting ?

### ISSUE THREAD

**Issue by wardhanster** [HenrikJoreteg/SimpleWebRTC#240]
I have been trying to get one way broadcasting working on my instance of this awesome project.
I have tried removing the local-video feed for the receiving end, via the medial options
  var mediaOptions = {
                          audio: true,
                          video: false
                          };
but thing is if more than two users are on the single room, a blank video div gets inserted into the application. And If I set audio to false , the whole thing stops working on the receiving end.

Any clues ?

**Comment by fippo** [comment]
you'll also want to set the receiveMedia options. It's quite possible that the blank video element (and stream) comes from the peers trying to establish a connection to each other.

Best way to prevent this should be not using the default "add videos to remoteVideos" but the more advanced way of hooking described in https://simplewebrtc.com/notsosimple.html#basic-overlay
(you should be able to access peer.stream and from there determine the number of audio tracks using peer.stream.getRemoteStreams() and .getRemoteStreams()[0].getAudioTracks() to identify your broadcaster

**Comment by wardhanster** [comment]
Thanks I got it working! :)
any hints on how to let user select the front and back camera ?

Regards

**Comment by xdumaine** [comment]
@wardhanster see [device selection](https://simplewebrtc.com/notsosimple.html#device-selection) for letting users choose the camera input.
