### ISSUE TITLE
Recording SimpleWebRTC call

### ISSUE THREAD

**Issue by shamun** [HenrikJoreteg/SimpleWebRTC#242]
I have a situation where i need to do recording. video + audio or audio only for every calls.

Scenario 1:

1 - User1 visit talky.io/test-recording
2 - User2 visit talky.io/test-recording
3 - on connect user1/2 recording starts
4 - On disconnect the recorded file is sent to 
A) Enterprise privacy cases (NAS server or via FTP Server) 
B) non privacy issue cases (Google Drive or DropBox)

Scenario 2:

1 - User1, User2, User3, User4 visit talky.io/test-mcu-recording
2 - On connect user1,2,3,4 video or audio only start recording
3 - On disconnect the recorded file is sent to 
A) Enterprise privacy cases (NAS server or via FTP Server) 
B) non privacy issue cases (Google Drive or DropBox)

Is it possible? how can you do that please?

**Comment by fippo** [comment]
see https://www.webrtc-experiment.com/RecordRTC/ or https://github.com/jitsi/jirecon

both require you to do work so are likely not what you're looking for.

**Comment by shamun** [comment]
How much disk space it require to record audio+video of an hour? or a minute please while using RecordRTC or JireCON?
