### ISSUE TITLE
How to use screen share?

### ISSUE THREAD

**Issue by eshengsky** [HenrikJoreteg/SimpleWebRTC#246]
I have use https both in my web site and webrtc server(https://localhost:8888), but when I start to share scrren(use webRtc.getLocalScreen()), Firefox console shows: 
PermissionDeniedError: The user did not grant permission for the operation.
How to resolve it? Thanks.

**Comment by fippo** [comment]
Firefox uses a whitelist mechanism for screensharing (see also https://github.com/henrikjoreteg/getscreenmedia and the sample extension). 

IIRC it is not possible to reliably determine the difference between a user denying (PermissionDeniedError) and not being on the whitelist.
@xdumaine came up with a neat hack here by observing that the timing in the latter case is inhumanly fast.

**Comment by eshengsky** [comment]
@fippo I understand what you said, and after I add 'localhost' to media.getusermedia.screensharing.allowed_domains config setting mumanually, it seems looks good.
But, I don't konw how to modify the setting automatically. I've download zip from https://github.com/henrikjoreteg/getscreenmedia ,and copy these files/folders to my project:
getscreenmedia.bundle.js & firefox-extension-sample folder
Then I changed: var domains = ["xxx.com"]; in bootstrap.js in firefox-extension-sample folder., and I reference the bootstrap.js and getscreenmedia.bundle.js.
But it still not working:( did I ignore something?
Could you please give the detail steps? Thanks very much!!

**Comment by xdumaine** [comment]
@eshengsky You don't need to reference bootstrap.js in the getscreenmedia.bundle.js file. Bootstrap.js is a part of the firefox extension, so it's used separately. In the [readme](https://github.com/HenrikJoreteg/getScreenMedia/blob/master/firefox-extension-sample/README.md) it has this line:

`zip simplewebrtc-screenshare.xpi bootstrap.js install.rdf` - you'll run that in the firefox extension directory, and it'll generate a .rdf file, which you can then install as an add-on in firefox via [about:addons](about:addons)

**Comment by eshengsky** [comment]
@xdumaine the domain has been added successfully! Thanks a lot!
And I wander if each user want to use screen share function, he/she must be install the addon I support? That's to say, I should give a download .xpi file link?

**Comment by xdumaine** [comment]
@eshengsky Your users would need the extension, but you shouldn't provide an XPI download to install. Ideally, you'd publish it in the firefox web store, and you could open the web store url in a new tab when the user first tries to start screen share and gets a near-instant failure. [Here](https://addons.mozilla.org/en-US/firefox/addon/screensharing-helper-for-purec/?src=search) is an example of a published add-on that uses the firefox sample.

**Comment by eshengsky** [comment]
@xdumaine Got it! Thanks!
