### ISSUE TITLE
How to stop by default AutoGainControl with SimpleWebRTC?

### ISSUE THREAD

**Issue by shamun** [HenrikJoreteg/SimpleWebRTC#248]
In Windows 8.1 Pro 64-bit i am having some serious audio issues.

1 - you talk near the microphone = Windows microphone volume control automatically lower down 
2 - you talk far away from the microphone = Windows microphone volume control automatically increase up

We hate this auto gain control, it completely destroy the audio quality and helps for nothing at all. How can i while using Talky or SimpleWebRTC permanently tell the framework please kindly stop doing this as default as it does not help at all instead creates a big audio issue.

Please kindly advise thank you.

**Comment by fippo** [comment]
https://github.com/HenrikJoreteg/SimpleWebRTC/issues/166#issue-44452958 -- isn't jonny another of your  sock puppets?

If AGC sucks, you should probably provide real feedback to the webrtc team instead of always complaining.

**Comment by brendensoares** [comment]
Is there not a way to disable gain correction?
