### ISSUE TITLE
webrtc.mute();

### ISSUE THREAD

**Issue by namnemet** [HenrikJoreteg/SimpleWebRTC#250]
webrtc.mute();
does not seem to work

i wanted all videos to be muted from the moment the page loads

called webrtc.mute(); from the outer scope

am i doing something wrong?

also tried:
webrtc.on('audioOff', function () {
    // your local audio just turned off
});

**Comment by fippo** [comment]
.mute() only mutes your own audio. If you don't want audio from the video elements, just set their volume to 0.

**Comment by namnemet** [comment]
sorry .... :-(

how do i do that?

**Comment by namnemet** [comment]
tried....
volume:0

no go...

**Comment by namnemet** [comment]
media: {
                video: true,
                audio: true
            }

:-) (from the repository examples - thank you)
