### ISSUE TITLE
peer.oneway

### ISSUE THREAD

**Issue by namnemet** [HenrikJoreteg/SimpleWebRTC#252]
what is peer.oneway 
if true
does it state that user A sees user B but not vice versa?

if so - where can i define the stream to work in such a way....?

Thank you

nami

**Comment by fippo** [comment]
apparently some cruft that was never implemented this way. Check the receiveMedia OfferToReceive* things in http://simplewebrtc.com/notsosimple.html#filetransfer for oneway streams.
