### ISSUE TITLE
What's the webrtc.getPeers equivalent?

### ISSUE THREAD

**Issue by JTallis** [HenrikJoreteg/SimpleWebRTC#256]
I was following the "not-so-simple" code and some of it is a little bit different. For instance

    webrtc.on('mute', function (data) { // show muted symbol
        webrtc.getPeers(data.id).forEach(function (peer) {
            if (data.name == 'audio') {
                $('#videocontainer_' + app.api.getDomId(peer) + ' .muted').show();
            } else if (data.name == 'video') {
                $('#videocontainer_' + app.api.getDomId(peer) + ' .paused').show();
                $('#videocontainer_' + app.api.getDomId(peer) + ' video').hide();
            }
        });
    });

webrtc.getPeers is not a function and I can't seem to find the suitable equivalent. Also in that snippet, `app.api.getDomId(peer)` should be `webrtc.getDomId(peer)`

What's the equivalent of webrc.getPeers, as it no longer exists?

---------------------

In the mean time, I added in my own loop but can also create a function for this too if you wish.

    webrtc.on('mute', function(data) {
        webrtc.webrtc.peers.foreach(function(peer) {
            if (peer.id == data.id) {
                 // Do stuff with peer
                return false;
            }
        });
    });

**Comment by fippo** [comment]
ah, decided to expose getPeers on webrtc -- published as 1.17.0
