### ISSUE TITLE
attach data to simpleWebRTC room or video

### ISSUE THREAD

**Issue by namnemet** [HenrikJoreteg/SimpleWebRTC#260]
i'm using simpleWebRTC for a multi-party video chat.

each user creates his own room. when a user subscribes to another (in order to see this person 0 and registers in the db).

when a user chooses another - he gets this users username by XHR from the db.

i tried attaching  the data for the appropriate div of each video (or room) - under the
webrtc.on('video added'......

is there a proper  way i can attach data to the video or room themselves - which will of course e more reliable

**Comment by fippo** [comment]
does 1.18.0 and http://simplewebrtc.com/notsosimple.html#nicknames address this?

**Comment by namnemet** [comment]
yes, it DOEEES ! :-)

thank you
