### ISSUE TITLE
sudden :Origin  therefore not allowed access

### ISSUE THREAD

**Issue by namnemet** [HenrikJoreteg/SimpleWebRTC#263]
i belive the only change i made was to start using cloudflare - a CDN service (and changing my name servers to theirs)

GET https://signaling.simplewebrtc.com/socket.io/1/?t=1434614931167 11.o.handshake @ simplewebrtc.bundle.min.js:111.o.connect @ simplewebrtc.bundle.min.js:2o @ simplewebrtc.bundle.min.js:111.n.connect @ simplewebrtc.bundle.min.js:1n @ simplewebrtc.bundle.min.js:1n @ simplewebrtc.bundle.min.js:1afterRoomDefined @ webrtc.js:28(anonymous function) @ webrtc.js:17m.Callbacks.j @ jquery.min.js:2m.Callbacks.k.fireWith @ jquery.min.js:2x @ jquery.min.js:4m.ajaxTransport.send.b @ jquery.min.js:4
face2face.php:1 XMLHttpRequest cannot load https://signaling.simplewebrtc.com/socket.io/1/?t=1434614931167. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://hubitus.com' is therefore not allowed access. The response had HTTP status code 502.

or signalmaster is down?

any idea ? :-(

**Comment by hardikbarot** [comment]
Any Solution???

**Comment by xdumaine** [comment]
Don't use the sandbox signaling server - set up your own instance of [SignalMaster](https://github.com/andyet/signalmaster/)

**Comment by namnemet** [comment]
can you point me to instructions on how set up my own instance of signalMaster?

**Comment by xdumaine** [comment]
It's a simple node server, you can host it however you like.

**Comment by namnemet** [comment]
i have PHP javaScript knowledge ....

**Comment by fippo** [comment]
it seems the sandbox server is down. But please... don't use the sandbox server.

**Comment by fippo** [comment]
should be back up thanks to @bear. Please reopen if it's not fixed.
