### ISSUE TITLE
Is one to one file sharing possible using SimpleWebrtc ? 

### ISSUE THREAD

**Issue by hanumesh** [HenrikJoreteg/SimpleWebRTC#265]

**Comment by fippo** [comment]
Did you see the filetransfer demo @ http://simplewebrtc.com/filetransfer.html?

**Comment by hanumesh** [comment]
yes . i missed it , thanks

**Comment by fippo** [comment]
http://simplewebrtc.com/notsosimple.html#filetransfer explains things even :-)

**Comment by hanumesh** [comment]
thanks , checked it
