### ISSUE TITLE
getUserMedia() constraints

### ISSUE THREAD

**Issue by namnemet** [HenrikJoreteg/SimpleWebRTC#266]
how can i use getUserMedia() constraints- frameRate (smaller frameRate) and maxWidth for the videos to conserves bandwidth when watching multiple videos

[and today in the newbie ridicules question section - does chrome automatically reduces video resolution according to the size i set in the CSS?]

1. does simpleWebRTC has something in the api for that?
2 . if not - can I use getUserMedia() or other commands with simpleWebRTC? 
if so how do i combine them together with simpleWebRTC

thank you

**Comment by xdumaine** [comment]
To set your media constraints for `getUserMedia`, pass them in the `media` option to the config

    var webrtc = new SimpleWebRTC({ media: { audio: true, video: true} });

**Comment by xdumaine** [comment]
To answer your second question, no - chrome will not automatically reduce the video size according to the size you set in css. You can resize a video element larger or smaller, but it won't change what is being captured or encoded and streamed.

**Comment by namnemet** [comment]
Thank you :-)
I was also interested in reducing frameRate - or anything else that might reduce the strain on the users computers or there bandwidth.

in your simple bundle i found:
video: {
                mandatory: {
                    chromeMediaSource: 'desktop',
                    maxWidth: window.screen.width,
                    maxHeight: window.screen.height,
                    maxFrameRate: 3
                },

that got me a bit confused - it says mandatory - but it is obviously not enforced... :-)
(would like to lower frame rate - is that possible?

do you have any other suggestion   i could reduce the strain (besides in addition to cutting frameRate as well)?


:-)

**Comment by xdumaine** [comment]
@namnemet It is enforced, actually. If the media devices available to the browser can't meet the requirements passed, an error occurs. See [this example](http://jsfiddle.net/xdumaine/3oueeahv/) that causes an error.

**Comment by xdumaine** [comment]
@namnemet See here where framerate is very low (5) and the video is very choppy because that's enforced by the getUserMedia capture: http://jsfiddle.net/xdumaine/xzm1x706/1/

**Comment by namnemet** [comment]
Thank you,
it works 

hmm ... 
if one plays the "lectures" and the others the "students" - i.e: they can all watch him - but he does not see their videos - can i make his video one directional? - and more importantly will that save some bandwidth? :-) :-)

Thank you so
