### ISSUE TITLE
Get peer connection information/IP address?

### ISSUE THREAD

**Issue by charliegreen** [HenrikJoreteg/SimpleWebRTC#267]
Hello!
I was wondering if there's a good way to get a peer's IP address/connection information, so a new data connection can be made outside of SimpleWebRTC? I'm writing an Android app that uses SimpleWebRTC in a WebView, but I need to open a connection from the Java side to the WebView's peer. I've been digging through SimpleWebRTC's code, but I can't find anything that seems like it would reliably work in future versions. Have I just not found the right documentation, or is this not currently possible? If it isn't, do you have suggestions on how I may implement it?
Thank you!

**Comment by fippo** [comment]
that can be extracted from the peer's peerconnection somehow (looking at either the SDP or using the getStats API), however that information will not be really useful outside the context of the peerconnection.

Did you consider using the datachannel to send over anything you need?

**Comment by charliegreen** [comment]
I tried using the datachannel first (via `webrtc.on('channelMessage', ...)` and `webrtc.sendDirectlyToAll(...)`; it works, but is this the best way to do it?), but I need to send a large volume of information, and I can't efficiently pass that information from the world of Java to the world of JavaScript due to limitations on data types with Android's JavascriptInterface. I was thinking that once the ICE channel gets determined, SimpleWebRTC must have some internal mechanism of opening a websocket or something to the other peer to establish the connection, which would mean that an IP address and port number must be floating around *somewhere*. Is that a correct assumption, or am I misunderstanding the protocols?

**Comment by fippo** [comment]
that internal mechanism is the RTCPeerConnection -- which transfers voice and video and data over a p2p connection. This P2P connection is using a port pair but not usable by other means.

Rather than sendDirectlyToAll (if you have many peers, this will be very inefficient since you send data multiple times on your upstream) you should use .getPeers() and .sendDirectly()

**Comment by charliegreen** [comment]
But to create that P2P connection, RTCPeerConnection must be holding an IP address somewhere in its depths; is there any way I could get that IP address from it, then connect to the peer on a different port? I have control over that peer. Thank you!

**Comment by fippo** [comment]
you can get an IP address, however it might be the ip address of a TURN relay for cases where both peers are behind NAT.

In chrome, the following will get you the IP you're connected to (test on https://simplewebrtc.com/demo.html)
webrtc.getPeers()[0].pc.pc.localDescription.sdp.split('\r\n').filter(function (line) { return line.indexOf('c=') === 0; })

**Comment by charliegreen** [comment]
Thank you!
I have this function now:
```
function getPeerIP() {
    var peers = webrtc.getPeers();
    if (peers && peers[0]) {
        var ips = peers[0].pc.pc.localDescription.sdp.split('\r\n').filter(function(line){
            return line.indexOf('c=') === 0;
        }).map(function(ipstr){
            return ipstr.match(/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/)[0];
        });
        return ips[0];
    }
    return ''; // no connected peers
}
```
I'm a bit confused about this, though; I'm seeing three identical 'c=...' lines in sdp, and they keep pointing to my own IP address. Why are there three lines? Is oneself counted as a peer in webrtc.getPeers()?
Thank you so much for all your help!

**Comment by charliegreen** [comment]
I gather from reading [this RFC](https://www.ietf.org/rfc/rfc2327.txt) that the three different sdp connection lines are for different media streams. It doesn't look like oneself is counted as a peer, though, so I'm still at a loss about that.

**Comment by charliegreen** [comment]
Ah. remoteDescription, not localDescription. Thank you!
