### ISSUE TITLE
How to replace Ip Address for peer-to-peer connection for media in WebRTC app?

### ISSUE THREAD

**Issue by KrishPS** [HenrikJoreteg/SimpleWebRTC#270]
I am writing WebRTC application for windows. My scenario is like:
1. LAN is default network interface for all applications. 
2. System has more than one network interfaces like LAN and Wifi or usb modem. 
3. WebRTC Signaling should use LAN & media (peer-to-peer connection) should use Wifi network. So that application can get fast network access for media communication.
Question- How to replace the Wifi Ip Address from LAN IP Address for media communication (peer-to-peer connection)?

My observation is:
1. It is possible to print Private and Public ICE candidates as per blow code. 
pc.onicecandidate = function(evt) {
if (evt.target.iceGatheringState == "complete") {
local.createOffer(function(offer) {
console.log("Offer with ICE candidates: " + offer.sdp);
signalingChannel.send(offer.sdp);
});
Private ICE candidate (192.168.1.73:60834) for the peer
Public ICE candidate (50.76.44.100:69834) returned by the STUN server.

2. Now how to replace the Private ICE conditate (IP Address) to Wifi (IP Address)?

Could you please suggest any solution?

**Comment by fippo** [comment]
Am 02.07.2015 um 14:38 schrieb KP Singh:
> I am writing WebRTC application for windows. My scenario is like:
> 1. System has more than one network interfaces like LAN and Wifi or usb modem.
> 2. WebRTC Signaling should use LAN & media (peer-to-peer connection) should use Wifi network. So that application can get fast network access for media communication.
> Question- How to replace the Wifi Ip Address from LAN IP Address for media communication (peer-to-peer connection)?
>
> My observation is:

You don't want to do that (i.e. non-trickle). Calling createOffer is not 
necessary if you already called setLocalDescription, the 
pc.localDescription will contain an sdp with all candidates.

> Private ICE candidate (192.168.1.73:60834) for the peer
> Public ICE candidate (50.76.44.100:69834) returned by the STUN server.
>
> 2. Now how to replace the Private ICE conditate (IP Address) to Wifi (IP Address)?

There should be an ice candidate with the Wifi IP (not sure how you want 
to determine that though).

What might work is looking at the message content in
https://github.com/HenrikJoreteg/SimpleWebRTC/blob/master/simplewebrtc.js#L150-152
and only signal the candidate with the wifi ip.
	
You probably need to filter out the srflx candidate from the non-wifi 
interface, too. This is tricky, you need to look for a candidate with 
the same foundation (see 
http://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) 
as your wifi candidate, as the foundation identifies the interface.

> Could you please suggest any solution?

this is going to be very complicated... hope that helps a little.

**Comment by fippo** [comment]
fixed per https://groups.google.com/forum/#!topic/discuss-webrtc/5Md1bDMI7Q0
