### ISSUE TITLE
Its not complain, but together improving the common statement for some networking specialists

### ISSUE THREAD

**Issue by shamun** [HenrikJoreteg/SimpleWebRTC#273]
Is this following content correct to share with some networking specialists in some enterprises? Please correct/edit the following. There are sometimes some Enterprise environment where Talky, SimpleWebRTC does not work or it worked and then you have low quality or connection dropping, then it turns out to be impossible to fix it, because networking team does not know what to look for or improve for.

Therefore, we are trying to make one statement for networking people to check and improve. Please advise.

--- start statement ---

A) SimplewebRTC - Optimize your network

Talky are adaptive in the ways they attempt to establish a network connection between a participant on your network and the Talky conference servers.

The connection methods are attempted in this preferenced order:

A UDP connection from the participant to talky on ports 19302 through 19309
A TCP connection from the participant to talky on ports 19305 through 19309
A TCP connection from the participant to talky on port 80
A TCP connection from the participant to talky on port 443 (SSL)

The ideal connection for a user to make to a Talky is through UDP. 
To allow this connection attempt to succeed, you must allow routes from your network to UDP ports 19302 through 19309.

At a minimum, your corporate network must allow access to the Internet on TCP ports 80 and 443 in order for Talky to work.

In addition, we recommend opening these additional ports on TCP for the following clients:

Ports	Clients
5222, 5223, 5224	XMPP clients
5228 and 5229	Android phones
5269	XMPP federation

Consult the documentation from your firewall vendor if you need information about opening UDP and TCP ports.
Notes

All traffic back to the client from Talky conference servers will originate from the same port that the client is sending to, and be directed back to the port that the client is sending from.

The UDP traffic consists of STUN, RTP, and RTCP packets, with SRTP encrypted data payloads.

We are unable to provide any specific IP addresses for our conference servers.

B) Requirements and specifications for video calls
There are a few specifications and limitations of video calls that you should be aware of:

Video calls can have a maximum of 10 participants.
You need to have a broadband connection to the Internet.
We recommend using USB web cameras and BlackMagic devices for the best video call experience. Other devices, like virtual cameras, may not work with Talky.

Processor Minimum Requirements:

Any 2 GHz dual core processor or greater.

Bandwidth

For 1:1 connections we suggest a 1 mbps/1 mbps (up/down)
For group video connectivity we suggest 1 mbps/2 mbps (up/down)

More details about bandwidth

The bandwidth used by Talky is adaptive and will vary to provide the best experience for the given conditions of the participants’ network. Here is a guide for the minimum and maximum bandwidth requirements and expectations:

Minimum bandwidth required:

Outbound from the participant: 300 kbps
Inbound to the participant: 300 kbps
Ideal bandwidth for the best experience:

Outbound from the participant: 2.6 mbps
Inbound to the participant: 2.6 mbps
With group video calls of more than 2 people you can expect bandwidth usage in ideal situations to be:

Outbound from the participant in all situations: 2.6 mbps
Inbound to the participant with 5 participants: 3.2 mbps
Inbound to the participant with 10 participants: 4.0 mbps

--- end of statement ---

**Comment by shamun** [comment]
??????????

**Comment by fippo** [comment]
> ??????????

Still considering what the proper response to this attempt to get me to 
do your work is.

The talky instructions are not part of this repository, your "statement" 
does not apply to the STUN/TURN configuration used there. And we don't 
recommend black magic devices, which are your favorite things.
