### ISSUE TITLE
How to increase the video quality to maximum, there is no bandwidth limitation.

### ISSUE THREAD

**Issue by shamun** [HenrikJoreteg/SimpleWebRTC#280]
In `PeerConnection.prototype.handleAnswer` i have set the BitRate to have video quality improve but it always using bandwidth 300 to 400Kb/s instead 1Mb or 2Mb. 

This https://www.webrtc-experiment.com/webrtcpedia/ page listed some min/max bitrate values for VP8 and Opus codecs. 20kbits is minimum bandwidth supported for VP8, and 30kbits is minimum for Opus. But i have LAN network in the co-location network/rack and i need to increase the bandwidth to maximum if i use above 1Mb it still use 300 to 400 Kb. 

```
Vp8 codec maximum bandwidth is 2000+ kbits/s
720p at 30 FPS causes 1.0-to-2.0 Mbps bandwidth usage
360p at 30 FPS causes 0.5-to-1.0 Mbps bandwidth usage
180p at 30 FPS causes 0.1-to-0.5 Mbps bandwidth usage
```

Can you please tell me what is going wrong ?

```
    function preferBitRate(sdp, bitrate, mediaType) {
      var sdpLines = sdp.split('\r\n');

      // Find m line for the given mediaType.
      var mLineIndex = findLine(sdpLines, 'm=', mediaType);
      if (mLineIndex === null) {
        console.log('Failed to add bandwidth line to sdp, as no m-line found');
        return sdp;
      }

      // Find next m-line if any.
      var nextMLineIndex = findLineInRange(sdpLines, mLineIndex + 1, -1, 'm=');
      if (nextMLineIndex === null) {
        nextMLineIndex = sdpLines.length;
      }

      // Find c-line corresponding to the m-line.
      var cLineIndex = findLineInRange(sdpLines, mLineIndex + 1, nextMLineIndex,
                                       'c=');
      if (cLineIndex === null) {
        console.log('Failed to add bandwidth line to sdp, as no c-line found');
        return sdp;
      }

      // Check if bandwidth line already exists between c-line and next m-line.
      var bLineIndex = findLineInRange(sdpLines, cLineIndex + 1, nextMLineIndex,
                                       'b=AS');
      if (bLineIndex) {
        sdpLines.splice(bLineIndex, 1);
      }

      // Create the b (bandwidth) sdp line.
      var bwLine = 'b=AS:' + bitrate;
      // As per RFC 4566, the b line should follow after c-line.
      sdpLines.splice(cLineIndex + 1, 0, bwLine);
      sdp = sdpLines.join('\r\n');
      return sdp;
    }


answer.sdp

```

**Comment by fippo** [comment]
this is not a simplewebrtc-issue afaics. Please use discuss-webrtc for general webrtc questions.

**Comment by shamun** [comment]
OK - we will discuss there. Do you have reference book or manual documentation on bitrate change for simplewebrtc?  so that it can be used and prepare to show discuss-webrtc for prove that its failing? i have not found any documentation of your library, you should know better then me where exactly the bitrate changes need to be applied before you throw me somewhere else to ask such questions related to simplewebrtc. NO?

**Comment by fippo** [comment]
apply your SDP changes to the http://webrtc.github.io/samples/src/content/peerconnection/munge-sdp/
this is not a question related to simplewebrtc.
