### ISSUE TITLE
Only works on one-to-one of which was to be many-to-many, webrtc

### ISSUE THREAD

**Issue by thebestclass** [HenrikJoreteg/SimpleWebRTC#282]
I am developing a conference style application (many-to-many) for video calls this style: [http://spaceify.net/talk/][1]. He even is available on **GitHub** but I can not for my nodejs to work, which is not much novelty, hence I decided to create my own using **PHP** that never leaves me.

I created the server using **WebSockets**, is simple he receives the message and forwards it to all connected .. Just that, nothing more nothing less.

But my problem is that it does not connect with more than one person, to connect with the third person other streams fail. You can only connect one-to-one.

I do not know consider whether the error is in JavaScript or some need to improve server .. What can I do to make it connect to all who come?

See my code:

    var socket = new WebSocket('ws://127.0.0.1:1805/');
    var stunServer = "stun.l.google.com:19302";
    var localStream = null;
    var peerConn = null;
    var started = null;
    var mediaConstraints = {
        'mandatory': {
            'OfferToReceiveAudio': true,
            'OfferToReceiveVideo': true
        }
    };
    
    function createPeerConnection() {
        var servers = [];
        servers.push({
            'url': 'stun:' + stunServer
        });
        var pc_config = {
            'iceServers': servers
        };
        peerConn = new webkitRTCPeerConnection(pc_config);
        peerConn.onicecandidate = function(event) {
            if (event.candidate) {
                sendMessage({
                    type: 'candidate',
                    label: event.candidate.sdpMLineIndex,
                    id: event.candidate.sdpMid,
                    candidate: event.candidate.candidate
                });
            }
        };
        peerConn.onaddstream = function(event) {
            console.log("Added remote stream");
            $("body").append('<video width="320" height="240" autoplay="true" src="' + window.URL.createObjectURL(event.stream) + '"></video>');
        };
        peerConn.onremovestream = function(event) {
            console.log("Remove remote stream");
        };
    }
    
    function sendMessage(message) {
        var mymsg = JSON.stringify(message);
        console.log("SEND: " + mymsg);
        socket.send(mymsg);
    }
    
    function connect() {
        if (localStream) {
            console.log("Creating PeerConnection.");
            createPeerConnection();
            console.log('Adding local stream...');
            peerConn.addStream(localStream);
            started = true;
            peerConn.createOffer(setLocalAndSendMessage, null, mediaConstraints);
        }
    }
        
    socket.addEventListener("message", function(evt) {
        console.log("RECEIVED: " + evt.data);
        processSignalingMessage(evt.data);
    }, false);
    
    function processSignalingMessage(message) {
        var msg = JSON.parse(message);
        if (msg.type === 'offer' && localStream && !started) {
            started = true;
            createPeerConnection();
            console.log('Adding local stream...');
            peerConn.addStream(localStream);
            peerConn.setRemoteDescription(new RTCSessionDescription(msg));
            console.log("Sending answer to peer.");
            peerConn.createAnswer(setLocalAndSendMessage, null, mediaConstraints);
        } else if (msg.type === 'answer') {
            peerConn.setRemoteDescription(new RTCSessionDescription(msg));
        } else if (msg.type === 'candidate') {
            var candidate = new RTCIceCandidate({
                sdpMLineIndex: msg.label,
                candidate: msg.candidate
            });
            peerConn.addIceCandidate(candidate);
        }
    }
    
    function setLocalAndSendMessage(sessionDescription) {
        peerConn.setLocalDescription(sessionDescription);
        sendMessage(sessionDescription);
    }
    
    function startVideo() {
        try {
            navigator.webkitGetUserMedia({
                audio: true,
                video: true
            }, successCallback, errorCallback);
        } catch (e) {
            navigator.webkitGetUserMedia("video,audio", successCallback, errorCallback);
        }
    
        function successCallback(stream) {
            $("body").append('<video width="320" height="240" autoplay="true" src="' + window.URL.createObjectURL(stream) + '"></video>');
            localStream = stream;
        }
    
        function errorCallback(error) {
            console.log('An error occurred: [CODE ' + error.code + ']');
        }
    }

full code here: http://pastebin.com/3iWDLU9Y

  [1]: http://spaceify.net/talk/

**Comment by fippo** [comment]
have you considered using a library to do this such as this one?

Currently, you're creating a single peerconnection object. But you need one peerconnection per pair of people that will get connected.

**Comment by thebestclass** [comment]
@fippo The library is very large, I would like something smaller and lighter.

You refer to this function of the code that must be recreated for each new connection?

`createPeerConnection`

**Comment by fippo** [comment]
it's large because it solves a bunch of problems... like working in Firefox which your code will not.
Anyway: yes, you might want to check http://webrtc.github.io/samples/src/content/peerconnection/multiple too

**Comment by thebestclass** [comment]
@fippo It is only a prototype, calm ... very good example I based myself in it and got something significant: I can connect one-to-one but when I connect the third person, the third person connects only with the first.

The first connects with the second and third.
The second connecting with the first.
The third connecting with the first.

I'm lost in solving this impasse ..

**Comment by xdumaine** [comment]
Adding a little context to this conversation, this is the StackOverflow post where I suggested to this user that SimpleWebRTC be used. http://stackoverflow.com/questions/31479356/

I'm closing this issue. The poster is asking for help restructuring basic PeerConnection code to support multiple user connections, which is exactly what this library solves, but then also says they don't want to use a library for "personal reasons." 

The answer is: a lot of work has gone into development of this library to solve the exact problem OP is asking us to solve (among others), and OP is welcome to take code or inspiration from this library (per the license).

**Comment by thebestclass** [comment]
I do not want to have to use such an extensive library of which I try to ride my own code. If not able to help, even though the solution I thank you for having closed this topic.

**Comment by thebestclass** [comment]
@xdumaine  I do not want to have to use such an extensive library of which I try to ride my own code. If not able to help, even though the solution to my problem, I thank you for having closed this topic.I seek help elsewhere, hugs.

**Comment by fippo** [comment]
@thebestclass: FWIW, you seem to be greatly underestimating the amount of time and effort it takes to write a webrtc library. This library is now more than two and a half years old and far from done.

**Comment by thebestclass** [comment]
@fippo  Nonsense, of course I'm not. But I think not necessary or useful to use something outsourced, and if you ever need maintenance? I will have to wait update you guys? I hope you understand.
