### ISSUE TITLE
channelMessage binary data

### ISSUE THREAD

**Issue by charliegreen** [HenrikJoreteg/SimpleWebRTC#283]
Hello! Is it possible to send raw binary data along channelMessage data channels, and how can this be done the most efficiently? In particular, I'm trying to send a Uint8Array through, but it seems to be transformed into a normal JavaScript array before transmission. Thank you!

**Comment by fippo** [comment]
did you look at the filetransfer sample and the implementation in https://github.com/HenrikJoreteg/SimpleWebRTC/blob/master/peer.js#L256 -- in particular https://github.com/otalk/filetransfer/blob/master/filetransfer.js#L64 ?

**Comment by charliegreen** [comment]
I just want to send a buffer, though, not a file; are you saying I should create an object that looks like a file object and fill it with my buffer somehow? How would I do that?
Also, I tried sending an ArrayBuffer, and all that came up on the other side was an empty object

**Comment by fippo** [comment]
no, sending a buffer should work -- but you need to be careful about the binaryType and probably can't use the sendDirectly which uses JSON.stringify by choice.

**Comment by charliegreen** [comment]
I think I mostly understand what you're saying, but I must have done something wrong, as I'm getting bizarre errors. On both sides, in the videoAdded event, I do something like this:
```javascript
var dc = peer.getDataChannel('binary');
dc.binaryType = 'arraybuffer';
dc.onopen = function() { console.log("dc open") };
dc.onclose = function() { console.log("dc close") };
dc.onmessage = function(msg) { console.log("dc message") };
binaryChannel = dc;
```
On one side, though, I also have this, which runs on pageload:
```javascript
document.getElementById('button').addEventListener('click', function(e){
    var foo = new Uint8Array([0,1,2,3,4,5,6,7,8,9]);
    if (binaryChannel) {
        binaryChannel.send(foo.buffer);
    }
});
```
When I load both pages, they connect to each other just fine, and both onopen events fire. When I hit the button, though, I get *this*, of all things, in the console of the other browser:
```
Uncaught SyntaxError: Unexpected token o
```
There's no stack trace, onmessage doesn't fire, and the given file and line number is index.html:1. The browser with the button is an Android WebView (so Chrome 43), and the other browser is Chromium 43. Any idea what I'm doing wrong, or how to debug this? Thanks!

**Comment by fippo** [comment]
i think i know what happens... on the peer, this will try to json-decode things by default.
You need to override the .onmessage in the on('channelOpen') I think, similar to what https://github.com/HenrikJoreteg/SimpleWebRTC/blob/master/peer.js#L76-88 does

**Comment by charliegreen** [comment]
That fixed it. Thank you!
