### ISSUE TITLE
Enable Media Automatically

### ISSUE THREAD

**Issue by edvardenz** [HenrikJoreteg/SimpleWebRTC#284]
Hi,

Is there a way in simplewebrtc to automatically enable the media request of browser?

To open the stream without having to click aways to enable camera and mic.

Thanks,
Best Regards.

**Comment by tgabi333** [comment]
chrome remembers permissions if you using https.

**Comment by fippo** [comment]
and Firefox has the option to remember it, it's just not the default

**Comment by xdumaine** [comment]
As of now, Edge will not remember permissions.

**Comment by edvardenz** [comment]
Hi,

Thanks for all replies...
It was very usefull.... 

Thanks,
Best regards
