### ISSUE TITLE
Video chat seems to be working in one direction only

### ISSUE THREAD

**Issue by rubencodes** [HenrikJoreteg/SimpleWebRTC#285]
I'm using the code in the not-so-simple page (http://simplewebrtc.com/notsosimple.html) e.g. where you specify the video element Id later in a block like:

```
webrtc = new SimpleWebRTC({
		  localVideoEl: "localVideo",
		  remoteVideosEl: "",
		  autoRequestMedia: false,
		  debug: false,
		  detectSpeakingEvents: true,
		  autoAdjustMic: false
});
webrtc.on('videoAdded', function (video, peer) {
    console.log('video added', peer);
    var remotes = document.getElementById('remotes');
    if (remotes) {
        var container = document.createElement('div');
        container.className = 'videoContainer';
        container.id = 'container_' + webrtc.getDomId(peer);
        container.appendChild(video);

        // suppress contextmenu
        video.oncontextmenu = function () { return false; };

        remotes.appendChild(container);
    }
});
```

On a button click I do:

```
webrtc.startLocalVideo();
webrtc.joinRoom(room);
```

However, the problem is that my video chat seems to be working in one direction only; the first user that enters the video chat *cannot* see the video of the second user, only their own local video, but the second user *can* see the video of the first user as well as their own local video. I checked the peers list on both clients, and they both start out empty and have 1 peer when the other user connects. But it seems the first user never has the second user's video feed show up. Any thoughts?

**Comment by fippo** [comment]
can you try moving the joinRoom to the .on('localStream')? Otherwise you might be running into timing issues

**Comment by rubencodes** [comment]
Wow! That worked perfectly! Thank you!
Small additional question, how can I check when another user has joined the room? e.g. alert User A when User B starts a video chat.
