### ISSUE TITLE
disable/enable video/audio without re-instantiating the webrtc-object

### ISSUE THREAD

**Issue by Goatic** [HenrikJoreteg/SimpleWebRTC#286]
Hello - love the project, have a question though.

I've set up routing in my web-application, and am trying to have the simpleWebRTC object instantiated only once, but by default with > Media{audio:false, video:false}... The issue is that I want to enable mic+cam when I join a room, and disable them again when I leave a room... Any suggestions?

really don't wanna have to create a new SimpleWebRTC-object whenever I join a room :(

**Comment by xdumaine** [comment]
Don't try to set media config to false. Instead, pass in the media options you want to use, and start/stop media on demand:

```javascript
var roomToJoin = null; // your own variable, not joining any room yet

var webrtc = new SimpleWebRTC({
    media: { audio: true, video: true },
    autoRequestMedia: false // already false by default
});

webrtc.on('readyToCall', function () {
    webrtc.joinRoom(roomToJoin);
});

// when you want to start video
document.getElementById('join-room').onclick = function () {
    roomToJoin = 'room A';
    webrtc.startLocalMedia();
};

// when you want to hang up
document.getElementById('hangup').onclick = function () {
    webrtc.stopLocalMedia();
};

**Comment by Goatic** [comment]
Thanks a lot for clearing this up for me :+1: 'startLocalMedia' has to be replaced with 'startLocalVideo' though :)
