### ISSUE TITLE
Forcing relay and testing connectivity with TURN server

### ISSUE THREAD

**Issue by Ijatsu** [HenrikJoreteg/SimpleWebRTC#291]
Hello,

I'm working with SimpleWebRTC and I'm at the point where I want to use my own TURN server.

First: I modified the signal master in order to allow the use of public TURN, they use public credentials instead of the authorization system. I would like to test if my system works with these servers.
How can I do that? Meaning how can I force the use of Turn servers?
I tried to set this variable after creating the SimpleWebRTC object
```javascript
simplewebrtc.webrtc.config.peerConnectionConfig.iceTransports = "relay";
```
With that, I get the "offer" and "answer" logs from SimpleWebRTC but not a single candidate appear, the video of the remote client appears but it stays black, there's no "fail" logs or anything informative. I tested this with 2 different public servers, if you have some more I would be glad to test with them too. Am I doing something wrong?
I do everything locally, what should I set on my firewall to force the use of Turn?

Then: When I am convinced that my system works with a TURN server I would like to test my own turn server (coturn) that I set with rest API enabled.

I tested with my current system already and the TURN server reacts and write logs about client connections but doesn't give more informations. Client side it fails the same way.

Thanks for your time!

**Comment by xdumaine** [comment]
What public TURN server are you trying to use?

**Comment by fippo** [comment]
if it's muaz khan's credentials that are floating around on the internet: they don't work.

For testing TURN servers, http://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ works nicely. If you get relay candidates, things work. If you don't...

**Comment by Ijatsu** [comment]
Hello,

Thanks for your quick responses!

I found a public turn server that works with the web tester you gave me :) Once put into my signaler's parameters I was able to make a connection while forcing relay!
Thanks for this it's really helping. It confirms that the force relay feature works.

If you want to know which is the public turn server, ask me. I'll now try to find out why my turn server doesn't work.

**Comment by Roarz** [comment]
Hey there Ijatsu,

I am also working on a WebRTC project. I was just wondering, what public turn server did you end up using as I am in a similar situation that you were in.

Regards
R

**Comment by pbojinov** [comment]
I was in the same boat looking for a good public TURN server but ended up using [Twilio's TURN/STUN servers](https://www.twilio.com/stun-turn). It's free as long as you don't put more than 1GB of traffic a month on the TURN server. After that, it ends up being cents per GB, pretty much free as long as you're not running a production load.

BTW I'm not paid, endorsed, or affiliated with Twilio in any way. Just trying to help others with something that worked for me.
