### ISSUE TITLE
TURN configuration for filetransfer?

### ISSUE THREAD

**Issue by cremfert** [HenrikJoreteg/SimpleWebRTC#297]
I have set up a signalmaster and a TURN server to ensure connectivity between two peers when doing a filetransfer with SimpleWebRTC.

My question now is: when I specify the "url" parameter when initializing the SimpleWebRTC object, is the TURN server configuration provided by the signalmaster also used for filetransfer? Or do I have to overwrite the peerConnectionConfig?

Thanks and best regards,
Chris

**Comment by fippo** [comment]
peerConnectionConfig (which is pushed down from signalmaster) is also used for filetransfer peerconnections -- no difference here from audio/video connections.

**Comment by cremfert** [comment]
Thanks a lot for the answer!
