### ISSUE TITLE
iOS version with cordova-iosrtc-plugin

### ISSUE THREAD

**Issue by cremfert** [HenrikJoreteg/SimpleWebRTC#303]
Dear all,
there is a plugin available for Cordova HTML5 apps, proposing to enable WebRTC API on IOS (https://github.com/eface2face/cordova-plugin-iosrtc)

I tried to run SimpleWebRTC with this plugin. I do not get any error on the console, even if I switch on "debug"-mode. Nothing actually happens, no output on console, no video, no connection to the signalmaster server.

Is there any chance to make SimpleWebRTC running with the plugin? Do you have a tip for me how I could start debugging SimpleWebRTC if no debug message is coming up? I would like to contribute to enhance SimpleWebRTC for mobile, but no debug messages make it hard for me to start. Is there maybe a "platform check" or something like that, hindering SimpleWebRTC to start on platforms like iOS?

Thanks and best regards,
Chris

**Comment by cremfert** [comment]
I just got it to work! But the problem is now, that the app works fine, if I disable audio in the media configuration part of the constructor. Then I can see the video and can here the remote partner. Of course, the partner cannot hear me. If I enable audio, the whole application stucks, as readyToCall is never fired. Seems that there is a problem with the access to the mic. With the test apps of iosrtc, everything works fine.

So my question: is there anything special with audio handling? I also saw something like "audiofallback" in LocalMedia. Might this be of interest for me?

Thanks and best regards,
Chris

**Comment by cremfert** [comment]
Found the problem: LocalMedia has this parameter:
```detectSpeakingEvents: true```
If I set this to false, everything works fine. Now my question is: is it possible to set this also in the SimpleWebRTC constructor configuration?

Best regards,
Chris

**Comment by fippo** [comment]
that suggests some incompability with webaudio
