### ISSUE TITLE
How to silence in multi conference by peer?

### ISSUE THREAD

**Issue by shamun** [HenrikJoreteg/SimpleWebRTC#305]
I have a situation like following for one pilot project, if its not possible we have to move away to some other solutions over H.323 or SIP where it is already exist.

1 - John, Albert, Laura, Silvia connected in MCU using SimpleWebRTC (for example Silvia is talking and everybody is listening)
2 - everybody can hear and can talk at the same time

But

3 - John wants to only listen Silvia (or selective individuals) but not Albert, Laura or anyone else going to join on that room

Is this possible with SimpleWebRTC to silence per peer while being in MCU?

**Comment by fippo** [comment]
simplewebrtc doesn't support any MCUs (multipoint control unit, a server where everyone sends data and that forwards a mixed stream) so I am not sure what you're talking about even...

**Comment by shamun** [comment]
OK - Thank you. you already answered it.
